name: OCaml CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1

      - run: opam install . --deps-only --with-test -y
      - run: opam install ocamlformat.0.28.1 -y
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
      - run: opam exec -- dune fmt
      - run: git diff --exit-code